# Generated by Django 5.0.6 on 2026-04-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
    ]
