# Generated by Django 6.0.4 on 2026-05-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_phoneotp_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='is_phone_verified',
        ),
    ]
