# Generated by Django 6.0.4 on 2026-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description for SEO and display.'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap Icons class, e.g. "bi-apple" or "bi-cup-straw".', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive categories are hidden from the storefront.'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description for SEO and display.'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap Icons class, e.g. "bi-apple" or "bi-cup-straw".', max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive subcategories are hidden from the storefront.'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='store_categ_is_acti_6b7482_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_active', 'sort_order'], name='store_subca_is_acti_b54ded_idx'),
        ),
    ]
