# Generated by Django 5.0.6 on 2026-05-15 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsubcategories/')),
                ('description', models.TextField(blank=True, help_text='Brief description for SEO and display.')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons class, e.g. "bi-apple" or "bi-cup-straw".', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sub-subcategories are hidden from the storefront.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='store.subcategory')),
            ],
            options={
                'verbose_name_plural': 'sub-subcategories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.subsubcategory'),
        ),
        migrations.AddIndex(
            model_name='subsubcategory',
            index=models.Index(fields=['is_active', 'sort_order'], name='store_subsu_is_acti_6750d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subsubcategory',
            unique_together={('name', 'subcategory')},
        ),
    ]
