# Generated by Django 5.0.6 on 2026-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_address'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_api_sou_5fdbc8_idx',
            old_name='store_produ_api_sou_3fd3fc_idx',
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
