# Generated by Django 5.0.6 on 2026-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_userprofile_address_source_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether confirmation email has been sent'),
        ),
        migrations.AddField(
            model_name='order',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Whether confirmation SMS has been sent'),
        ),
    ]
