# Generated by Django 5.0.6 on 2026-06-17 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_email_sent_order_sms_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether all notifications have been sent'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of email delivery', max_length=20)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of SMS delivery', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, help_text='When the SMS was successfully sent', null=True)),
                ('email_error_message', models.TextField(blank=True, help_text='Error message if email sending failed')),
                ('sms_error_message', models.TextField(blank=True, help_text='Error message if SMS sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='store_notif_order_i_e15ee6_idx')],
            },
        ),
    ]
