# Generated by Django 5.0.6 on 2026-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_notification_sent_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='External video URL (e.g. YouTube embed or direct video link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, help_text='Upload a product video (MP4, WebM, etc.)', null=True, upload_to='products/videos/'),
        ),
    ]
