# Generated by Django 5.0.6 on 2026-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_add_product_video_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]