# Generated by Django 5.0.6 on 2026-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_add_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notifications were sent', null=True),
        ),
    ]
