# Generated by Django 5.0.6 on 2026-06-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Courier tracking number', max_length=100)),
                ('delivery_partner', models.CharField(blank=True, help_text='Courier partner name (e.g., Delhivery, Blue Dart)', max_length=100)),
                ('current_location', models.CharField(blank=True, help_text='Current location of the package', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal delivery notes')),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='store.order')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Tracking',
            },
        ),
        migrations.CreateModel(
            name='OrderTrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this status update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.ordertracking')),
            ],
            options={
                'verbose_name': 'Order Tracking History',
                'verbose_name_plural': 'Order Tracking Histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['status'], name='store_order_status_b95a41_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['tracking_number'], name='store_order_trackin_ec6020_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertrackinghistory',
            index=models.Index(fields=['tracking', 'created_at'], name='store_order_trackin_24781f_idx'),
        ),
    ]
