# Generated by Django 5.0.6 on 2026-06-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number')], default='email', help_text='Which contact method was chosen for signup verification.', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the selected verification was completed.', null=True),
        ),
    ]
