# Generated by Django 5.0.6 on 2026-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_profile_verification_method_profile_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the user completed profile-level verification.', null=True),
        ),
    ]
