# Generated by Django 5.0.3 on 2026-07-01 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_savedaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (entered by customer)', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Flat amount or percentage value', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order subtotal to use this coupon', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='How many times this coupon has been used')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Display description for the coupon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code used for this order', max_length=20),
        ),
    ]
