# Generated by Django 5.0.6 on 2026-07-23 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_seed_coupons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(help_text='Date of login')),
                ('login_time', models.TimeField(help_text="Time of login (user's local timezone)")),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State from IP geolocation', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100)),
                ('login_method', models.CharField(choices=[('password', 'Email/Password'), ('otp', 'Phone OTP'), ('google', 'Google OAuth'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('other', 'Other')], default='password', max_length=20)),
                ('security_status', models.CharField(choices=[('success', 'Successful Login'), ('new_device', 'New Device Login'), ('new_browser', 'New Browser Login'), ('new_location', 'New Location Login'), ('suspicious', 'Suspicious Login')], default='success', max_length=20)),
                ('is_new_device', models.BooleanField(default=False, help_text='First time login from this device')),
                ('is_new_browser', models.BooleanField(default=False, help_text='First time login from this browser')),
                ('is_new_location', models.BooleanField(default=False, help_text='First time login from this city/country')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether login alert email was sent')),
                ('sms_sent', models.BooleanField(default=False, help_text='Whether login alert SMS was sent')),
                ('email_error', models.TextField(blank=True, help_text='Error message if email sending failed')),
                ('sms_error', models.TextField(blank=True, help_text='Error message if SMS sending failed')),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_is_acti_6b7482_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicehistory',
            name='store_invoi_order_i_733d48_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicehistory',
            name='store_invoi_invoice_ab773a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='store_notif_order_i_e15ee6_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderstatushistory',
            name='store_order_order_i_e4d6fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordertrackinghistory',
            name='store_order_trackin_24781f_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedaddress',
            name='store_saved_user_id_1d53d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedaddress',
            name='store_saved_user_id_1f85b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='subcategory',
            name='store_subca_is_acti_b54ded_idx',
        ),
        migrations.RemoveIndex(
            model_name='subsubcategory',
            name='store_subsu_is_acti_6750d4_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='generated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='invoice_type',
            field=models.CharField(choices=[('original', 'Original'), ('regenerated', 'Regenerated')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sms_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='delivery_partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertrackinghistory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='bounding_box',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', '-created_at'], name='store_login_user_id_919462_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'country', 'city'], name='store_login_user_id_213623_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['is_new_device', 'is_new_browser', 'is_new_location'], name='store_login_is_new__23cbde_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['email_sent', 'sms_sent'], name='store_login_email_s_5b4af1_idx'),
        ),
    ]
