"""
Django settings for grocery_store project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv



load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "https://groc-production-6c7e.up.railway.app",
    "https://*.railway.app",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_celery_results',
    'store.apps.StoreConfig',
    'api_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grocery_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_context',
                'store.context_processors.categories_context',
                'store.context_processors.notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'grocery_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'grocery-api-cache',
    }
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Stripe
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_CURRENCY = os.getenv('STRIPE_CURRENCY', 'inr')
STRIPE_MINIMUM_PAYMENT_AMOUNT = os.getenv('STRIPE_MINIMUM_PAYMENT_AMOUNT', '50.00')

# RapidAPI Grocery API
GROCERY_API_ENABLED = os.getenv('GROCERY_API_ENABLED', 'True').lower() in ('1', 'true', 'yes', 'on')
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY', '')
RAPIDAPI_HOST = os.getenv('RAPIDAPI_HOST', 'grocery-api2.p.rapidapi.com')
GROCERY_API_COUNTRY = os.getenv('GROCERY_API_COUNTRY', 'us')
GROCERY_API_CACHE_SECONDS = int(os.getenv('GROCERY_API_CACHE_SECONDS', '1800'))
GROCERY_API_FAILURE_CACHE_SECONDS = int(os.getenv('GROCERY_API_FAILURE_CACHE_SECONDS', '300'))
GROCERY_API_RATE_LIMIT_PAUSE_SECONDS = int(os.getenv('GROCERY_API_RATE_LIMIT_PAUSE_SECONDS', '900'))
GROCERY_API_FORBIDDEN_PAUSE_SECONDS = int(os.getenv('GROCERY_API_FORBIDDEN_PAUSE_SECONDS', '3600'))

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '2525'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_OTP_SHOW_ON_DELIVERY_FAILURE = os.getenv('EMAIL_OTP_SHOW_ON_DELIVERY_FAILURE', 'False').lower() in ('1', 'true', 'yes', 'on')

# Login redirect
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Twilio configuration
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# Site URL for email links
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# Support contact
SUPPORT_PHONE_NUMBER = os.getenv('SUPPORT_PHONE_NUMBER', '+91-XXXXX-XXXXX')

# User profile signals
from django.contrib.auth import signals

from dotenv import load_dotenv
import os

load_dotenv()

# ---------------------------------------------------------------------------
# Celery Configuration
# ---------------------------------------------------------------------------
# For development on Windows without Redis/RabbitMQ installed, the broker URL
# can be left empty or set to a memory/DB transport. However, for production
# you MUST install Redis (recommended) or RabbitMQ and set a proper broker URL.
#
# Installation guides:
#   - Redis on Windows: Install WSL2 + Ubuntu, then `sudo apt install redis`
#   - Redis on Linux/macOS: `sudo apt install redis` or `brew install redis`
#   - RabbitMQ: https://www.rabbitmq.com/download.html
#
# Recommended broker URL formats:
#   Redis (local):    redis://localhost:6379/0
#   Redis (auth):     redis://:password@host:port/0
#   RabbitMQ (local): amqp://guest:guest@localhost:5672//
#   RabbitMQ (cloud): amqp://user:pass@host:port/vhost
#   AWS SQS:          sqs://aws_key:aws_secret@
#   Azure SB:         azureservicebus://connection_string
#
# If you do NOT have a broker running, Celery tasks will still be dispatched
# safely. The `safe_delay` helper in store/tasks.py will catch the broker
# connection error, log it, and fall back gracefully WITHOUT crashing the
# request-response cycle.
#
# The broker_connection_retry_on_startup=False prevents the worker itself
# from crashing if the broker is unavailable at worker startup time.

import ast

# Resolve broker URL: use REDIS_URL if set, else CELERY_BROKER_URL from env
# If no broker URL is configured, use 'cache+memory://' for development
# which requires no external service.
_CELERY_BROKER_URL = os.getenv('REDIS_URL') or os.getenv('CELERY_BROKER_URL', '')

# If no broker URL is configured at all, use an in-memory cache-based
# transport. This works out of the box with no external dependencies.
# For production: set REDIS_URL or CELERY_BROKER_URL in .env
if not _CELERY_BROKER_URL:
    _CELERY_BROKER_URL = 'cache+memory://'  # In-memory transport, no external service needed

CELERY_BROKER_URL = _CELERY_BROKER_URL
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ast.literal_eval(os.getenv('CELERY_ACCEPT_CONTENT', "['json']"))
CELERY_TASK_SERIALIZER = os.getenv('CELERY_TASK_SERIALIZER', 'json')
CELERY_RESULT_SERIALIZER = os.getenv('CELERY_RESULT_SERIALIZER', 'json')
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'Asia/Kolkata')
CELERY_ENABLE_UTC = os.getenv('CELERY_ENABLE_UTC', 'True').lower() in ('1', 'true', 'yes', 'on')

# Retry policy for Celery broker connection
# If the broker is temporarily down, Celery will retry connecting
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = os.getenv(
    'CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP', 'False'
).lower() in ('1', 'true', 'yes', 'on')

# Task routing — send auth-related tasks to a specific queue (optional)
CELERY_TASK_DEFAULT_QUEUE = os.getenv('CELERY_TASK_DEFAULT_QUEUE', 'default')
CELERY_TASK_DEFAULT_EXCHANGE = os.getenv('CELERY_TASK_DEFAULT_EXCHANGE', 'default')
CELERY_TASK_DEFAULT_ROUTING_KEY = os.getenv('CELERY_TASK_DEFAULT_ROUTING_KEY', 'default')

# Worker configuration
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_WORKER_MAX_TASKS_PER_CHILD', '50'))
CELERY_WORKER_SEND_TASK_EVENTS = os.getenv('CELERY_WORKER_SEND_TASK_EVENTS', 'True').lower() in ('1', 'true', 'yes', 'on')

# Task result expiration (in seconds) — 1 day default
CELERY_RESULT_EXPIRES = int(os.getenv('CELERY_RESULT_EXPIRES', '86400'))

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'api_settings.log',
            'formatter': 'verbose',
        },
        'notification_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'notifications.log',
            'formatter': 'verbose',
        },
        'celery_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'celery.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'api_settings': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'services.email_service': {
            'handlers': ['console', 'notification_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.sms_service': {
            'handlers': ['console', 'notification_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.notification_service': {
            'handlers': ['console', 'notification_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'store.notifications': {
            'handlers': ['console', 'notification_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'store.auth_emails': {
            'handlers': ['console', 'notification_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'store.tasks': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'kombu': {
            'handlers': ['console', 'celery_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}